version: '3.8'

services:
  ui:
    build: 
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REMOTE_ACTION_URL=http://agent:8000/copilotkit
    env_file:
      - ./ui/.env
    depends_on:
      - agent

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./agent/.env
    volumes:
      # Using absolute paths and ensuring directories exist
      - ${PWD}/chat_outputs:/asset/chat_outputs
      - ${PWD}/reports:/asset/reports
    environment:
      - HOST_PWD=${PWD}