version: '3.8'

services:
  ui:
    build: 
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REMOTE_ACTION_URL=http://agent:8000/copilotkit
    env_file:
      - ./ui/.env
    depends_on:
      - agent

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./agent/.env
    volumes:
      - ./reports:/asset/reports  # Mount the reports directory